### ISSUE TITLE
Plz Help!!! Speed logic

### ISSUE THREAD

**Issue by Sanketjr30** [dhananjaymenon/SpeedRadar-OpenCV-#6]
Any Specific logic or formula you used to calculate speed ie: 214 .
If you could explain will be better for me to work with other video

**Comment by dhananjaymenon** [comment]
An easy way to go about it is to estimate the speed of the first vehicle and work backwords from there to reach a constant.

If you know the first car in the picture is going 80 km/hr, then set a constant so that it shows that the vehicle is going 80km/hr.
After that, it will detect speed of the other vehicles

**Comment by Sanketjr30** [comment]
Ok but how can I find speed of first Vehicle..
Can you plz share yours whatsapp num or insta id i will ping my issues there.

**Comment by dhananjaymenon** [comment]
I estimated the speed of the first vehicle. It is not very accurate. This code works well with one video (as constants in the code have to be changed depending on the video)

**Comment by Sanketjr30** [comment]
Can you plz share me yours whatsapp num ..so that I can ping you there

**Comment by Sanketjr30** [comment]
Badly needed your help with that speed constant I could rectify it anyway..plz share yours number will be much helpful

**Comment by dhananjaymenon** [comment]
My number is +1 773 231 3263
